### PR TITLE
Bug - Sorting FDB table by devices

### LINKED ISSUE #16110: FDB Table sort by device zeros out results.
### The problem

When you go to Overview>FDB Tables, perform a search, and click on the "Device" header to sort by Device, the results blank out.

### Output of ./validate.php

```txt
librenms@librenms:~$ ./validate.php 
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.5.0-39-g3ad5bbc83 (2024-06-10T17:06:19-07:00)
DB Schema | 2024_04_29_183605_custom_maps_drop_background_suffix_and_background_version (294)
PHP       | 8.1.2-1ubuntu2.17
Python    | 3.10.12
Database  | MariaDB 10.6.16-MariaDB-0ubuntu0.22.04.1
RRDTool   | 1.7.2
SNMP      | 5.9.1
===========================================

[OK]    Composer Version: 2.7.7
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database Schema is current
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    Database and column collations are correct
[OK]    Database schema correct
[OK]    MySQL and PHP time match
[OK]    Active pollers found
[OK]    Dispatcher Service not detected
[OK]    Locks are functional
[OK]    Python poller wrapper is polling
[OK]    Redis is unavailable
[OK]    rrd_dir is writable
[OK]    rrdtool version ok
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX]: 
	You can fix this with ./scripts/github-remove
	Modified Files:
	 includes/definitions/discovery/deltaups.yaml
	 includes/definitions/discovery/procurve.yaml
```

### What was the last working version of LibreNMS?

_No response_

### Anything in the logs that might be useful for us?

```txt
Call to a member function getShortLabel() on int {"userId":6,"exception":"[object] (Error(code: 0): Call to a member function getShortLabel() on int at /opt/librenms/app/Http/Controllers/Table/FdbTablesController.php:187)"}
```

### PR DESCRIPTION
**Pull request by PipoCanaja**
fixes #16110 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [x] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

File: app/Http/Controllers/Table/FdbTablesController.php [hunk 1]
```diff
@@ -182,14 +182,14 @@ public function formatItem($fdb_entry)
         if ($fdb_entry->created_at) {
             $item['first_seen'] = $fdb_entry->created_at->toDateTimeString();
         }
-
         if ($fdb_entry->port) {
-            $item['interface'] = Url::portLink($fdb_entry->port, $fdb_entry->port->getShortLabel());
-            $item['description'] = $fdb_entry->port->ifAlias;
-            if ($fdb_entry->port->ifInErrors > 0 || $fdb_entry->port->ifOutErrors > 0) {
-                $item['interface'] .= ' ' . Url::portLink($fdb_entry->port, '<i class="fa fa-flag fa-lg" style="color:red" aria-hidden="true"></i>');
+            $port = Port::where('port_id', $fdb_entry->port_id)->first();
```
Comment (PipoCanaja) [inline app/Http/Controllers/Table/FdbTablesController.php:186]: if somebody knows why I can't use the relation to get the port here as it used to be ... At least this fix removes the exception, but I feel bad doing this :)

Comment (murrant) [reply app/Http/Controllers/Table/FdbTablesController.php:186]: Something is fishy.  The relationship is being used above here.

**Review by murrant — APPROVED** [review]

File: app/Http/Controllers/Table/FdbTablesController.php (hunk 1 above)
Comment (murrant) [reply app/Http/Controllers/Table/FdbTablesController.php]: The left join with the device was pulling in a "port" field which then caused Eloquent to think the port relationship was already loaded.
