### PR TITLE
Fix for linkDown/linkUp ifOperStatus

### LINKED ISSUE #15815: SNMP Trap LinkDown Incompatibility with RFC 2863
### The problem

[The SNMP Trap RFC](https://datatracker.ietf.org/doc/html/rfc2863) States:

```
linkDown NOTIFICATION-TYPE
    OBJECTS { ifIndex, ifAdminStatus, ifOperStatus }
    STATUS  current
    DESCRIPTION
            "A linkDown trap signifies that the SNMP entity, acting in
            an agent role, has detected that the ifOperStatus object for
            one of its communication links is about to enter the down
            state from some other state (but not from the notPresent
            state).  This other state is indicated by the included value
            of ifOperStatus."
    ::= { snmpTraps 3 }

linkUp NOTIFICATION-TYPE
    OBJECTS { ifIndex, ifAdminStatus, ifOperStatus }
    STATUS  current
    DESCRIPTION
            "A linkUp trap signifies that the SNMP entity, acting in an
            agent role, has detected that the ifOperStatus object for
            one of its communication links left the down state and
            transitioned into some other state (but not into the
            notPresent state).  This other state is indicated by the
            included value of ifOperStatus."
    ::= { snmpTraps 4 }
```

This means that in the LinkDown trap, the value of `ifOperStatus` is not the ***current*** value of `ifOperStatus`, its intended to be the "other state", which devices which implement the RFC correctly may state is "Up". 

The LinkDown handler sets the value of `port->ifOperStatus` to this value in the trap

```
        $port->ifOperStatus = $trap->getOidData("IF-MIB::ifOperStatus.$ifIndex") ?: 'down';
```

https://github.com/librenms/librenms/blob/b0c0530ec1389a2d5e1af4e47dbadf5ca9f05fd4/LibreNMS/Snmptrap/Handlers/LinkDown.php#L56C1-L57C1

Going off the RFCs description, this should always set the port->ifOperStatus to "down", and not be conditional on the value in the trap. 

### Output of ./validate.php

```txt
NA
```

### What was the last working version of LibreNMS?

_No response_

### Anything in the logs that might be useful for us?

```txt
NA
```

### PR DESCRIPTION
**Pull request by PipoCanaja**
Fix for RFC compliance

fixes #15815 

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [x] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [x] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

File: LibreNMS/Snmptrap/Handlers/LinkUp.php [hunk 1]
```diff
@@ -53,7 +53,7 @@ public function handle(Device $device, Trap $trap)
             return;
         }
 
-        $port->ifOperStatus = $trap->getOidData("IF-MIB::ifOperStatus.$ifIndex") ?: 'up';
```
Comment (laf) [inline LibreNMS/Snmptrap/Handlers/LinkUp.php:56]: From reading the issue it looks like up should still use what's in the trap, it's just the down one that needs to change.

Comment (PipoCanaja) [reply LibreNMS/Snmptrap/Handlers/LinkUp.php:56]: Indeed ! I should stop trying to use my brain after midnight for a while , I guess :D 
Will try to fix that now (breaking the above statement already :) )

**Review by Jellyfrog — APPROVED** [review]
