### PR TITLE
Fix for Cisco Transceivers

### LINKED ISSUE #16489: New Transceivers feature does not show any Graphs
### The problem

Updated to 24.9.1 to get the really cool new Transceiver feature - https://github.com/librenms/librenms/pull/16456
In the Host Overview, i got only some details of the Transceivers, but nothing more: 
Selection_20241003_001
Why are no Graphs show displayed? Do i have to enable some module or sensor?
However, optics are well monitored:
Selection_20241003_002

Thank you very much, for your great work!

### Output of ./validate.php

```txt
===========================================
Component | Version
--------- | -------
LibreNMS  | 24.9.1 (2024-09-30T01:40:22+02:00)
DB Schema | 2024_03_27_123152_create_transceivers_table (302)
PHP       | 8.2.23
Python    | 3.9.2
Database  | MariaDB 10.5.23-MariaDB-0+deb11u1
RRDTool   | 1.7.2
SNMP      | 5.9
===========================================

[OK]    Composer Version: 2.7.9
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database connection successful
[WARN]  Your database schema has extra migrations (2023_11_27_163400_increase_syslog_fields, 2023_12_11_165800_increase_syslog_fields). If you just switched to the stable release from the daily release, your database is in between releases and this will be resolved with the next release.
[OK]    SQL Server meets minimum requirements
[OK]    lower_case_table_names is enabled
[OK]    MySQL engine is optimal
[OK]    MySQL and PHP time match
[OK]    Distributed Polling setting is enabled globally
[OK]    Connected to rrdcached
[OK]    Active pollers found
[OK]    Dispatcher Service is enabled
[OK]    Locks are functional
[OK]    Python wrapper cron entry is not present
[OK]    Redis is functional
[OK]    rrdtool version ok
[OK]    Connected to rrdcached
```

### What was the last working version of LibreNMS?

24.9.1

### Anything in the logs that might be useful for us?

_No response_

### PR DESCRIPTION
**Pull request by PipoCanaja**
fixes #16489 

Some Cisco Transceivers are not mapped correctly because the Entity structure is as logical as expected : 
image

This code is an attempt to fix it and map correctly the Transceiver table and fix the display in LibreNMS GUI.

Before:
Capture d’écran 2024-12-10 à 12 38 21

After :
Capture d’écran 2024-12-10 à 12 39 59

This code also handles QSFP to SFP adapters. That means QSFP container contains SFP container contains SFP itself: 
image

DO NOT DELETE THE UNDERLYING TEXT

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

File: LibreNMS/OS/Shared/Cisco.php [hunk 1]
```diff
@@ -641,6 +641,10 @@ public function discoverTransceivers(): Collection
             $data = $this->getDevice()->entityPhysical()->whereIn('entPhysicalContainedIn', $dbSfpCages->keys())->get()->map(function ($ent) use ($dbSfpCages) {
                 if (empty($ent->ifIndex) && $dbSfpCages->has($ent->entPhysicalContainedIn)) {
                     $ent->ifIndex = $dbSfpCages->get($ent->entPhysicalContainedIn);
+                    if (empty($ent->ifIndex)) {
+                        // Lets try to find the 1st subentity with an ifIndex below this one and use it. A few ISR on IOSXE at least are behaving like this.
+                        $ent->ifIndex = $this->getDevice()->entityPhysical()->whereIn('entPhysicalContainedIn', [$ent->entPhysicalIndex])->whereNotNull('ifIndex')->first()->ifIndex;
```
Comment (murrant) [inline LibreNMS/OS/Shared/Cisco.php:646]: It would be better to do one query to make a map then a query for each transceiver.

Comment (PipoCanaja) [reply LibreNMS/OS/Shared/Cisco.php:646]: Yep, makes sense. Trying to check first if I have regressions or not (and fight with my test-data generation currently). But will do before removing WIP

Comment (PipoCanaja) [reply LibreNMS/OS/Shared/Cisco.php]: In fact, computing all the values when we may only need a couple (you normally have a bunch of ENTITY entries compared to the number of SFPs, even more if you consider this code is so far only necessary on ASRs and ISR which usually have only a small number of SFPs) is probably not the best idea. And I don't see an easy way to change the request to achieve it anyway. 
Still looking at that.

**Comment by PipoCanaja** [comment]
Do you have any idea how to troubleshoot this error ? iosxe_c9800 is clearly not empty, and should not be (both discovery and poller of course).
```
There was 1 failure:

1) LibreNMS\Tests\OSModulesTest::testOS with data set "iosxe_c9800" ('iosxe', 'c9800', array(true, true, true, true, true, true, true, true, true, true, true, true, true, true))
OS iosxe: Polled os generates data when none is expected
Failed asserting that null is not null.
```

File: LibreNMS/Modules/Transceivers.php [hunk 2]
```diff
@@ -41,7 +41,7 @@ class Transceivers implements Module
 
     public function dependencies(): array
     {
-        return ['ports'];
+        return ['ports', 'entity-physical'];
```
Comment (murrant) [inline LibreNMS/Modules/Transceivers.php:44]: I think I wrote the code to avoid this dependency.  It will use the DB if available, otherwise it will run snmp queries.

Comment (PipoCanaja) [reply LibreNMS/Modules/Transceivers.php:44]: OK, I'll remove it. Tests should still pass successfully If I did not mess up :)

Comment (PipoCanaja) [reply LibreNMS/Modules/Transceivers.php]: After removing it, it seems that comware does need this dependency to have the expected result. So we can 
- ignore it (and I revert comware tests) 
- force it for everybody 
- force it on an OS base (like force it for comware, but not for ciscoShared ?)

Comment (PipoCanaja) [reply LibreNMS/Modules/Transceivers.php]: removing the dependency breaks it again (at least for ASR9k), and I can't tell if the issue is with the tests processing or if it is a really issue with the code. I can't reproduce it locally. 
Any reason to avoid the dependency ? Cause adding it makes the tests more predictable, and removes redundant code anyway ...

**Comment by PipoCanaja** [comment]
So without the dependency, the tests are run in that order (skipping the ones that are not interesting in that case): 
- transceivers
- sensors
- entity-physical

Which is not the same as the order save-test-data.php runs. 

So without the dependency, I have no way to create a working file (except if I do it manually but it makes no sense).

**Comment by murrant** [comment]
Probably a good idea to fix the default order.  This is defined in config_defintions.json.  What is the intended order? I'm not quite sure.

I wonder if the order of the module in the json file affects the order in tests.

**Comment by PipoCanaja** [comment]
So : 
Order in config_definitions.json: 
```
110 - EntityPhysical
240 - Ports
280 - Sensors
322 - Transceivers
```
Order in the asr9001.json variant:
```
    "os": {
    "ports": {
    "processors": {
    "mempools": {
    "vrf": {
    "sensors": {
    "bgp-peers": {
    "entity-physical": {
    "cisco-pw": {
    "transceivers": {
```
And order in the tests running : 

```
#### Load disco module core ####
#### Load disco module os ####
#### Load disco module ports ####
#### Load disco module processors ####
#### Load disco module mempools ####
#### Load disco module vrf ####
#### Load disco module transceivers ####
#### Load disco module sensors ####
#### Load disco module ipv4-addresses ####
#### Load disco module ipv6-addresses ####
#### Load disco module bgp-peers ####
#### Load disco module entity-physical ####
#### Load disco module cisco-pw ####
```

I'll try a few things see if it improves things: 
- delete the file completely and re-generate it
- reorder the file manually to have all modules in the same order as the expected one.

**Comment by PipoCanaja** [comment]
OK. In fact, all this ends up in  `function discover_device(&$device, $force_module = false)` 
and the list is built like so : 
`$discovery_modules = ['core' => true] + Config::get('discovery_modules', []);`
without the use of the priorities at all. 
So order may even be random at some point, and currently only depends on the order of the `Config::get`.

**Comment by murrant** [comment]
> Order in config_definitions.json:
> 
> ```
> 110 - EntityPhysical
> 240 - Ports
> 280 - Sensors
> 322 - Transceivers
> ```

Uh, this isn't order of execution, it is order of display in the webui.

```
1417: ports
1438: transceviers
1445: entity-physical
1564: sensors
```

The entity-physical one seems like it should be before transceivers...

**Comment by murrant** [comment]
Looks like there is a bug in the phpunits not respecting the order as defined in config_definitions.json too.

**Comment by PipoCanaja** [comment]
Looks like it is ready for review.

File: tests/OSModulesTest.php [hunk 3]
```diff
@@ -98,6 +98,10 @@ public function testOS($os, $variant, $modules): void
         $this->requireSnmpsim();  // require snmpsim for tests
         // stub out Eventlog::log and Fping->ping, we don't need to store them for these tests
         $this->stubClasses();
+        // Order modules following both disovery and poller
```
Comment (murrant) [inline tests/OSModulesTest.php:101]: I don't think this is the correct place for this. I'll try to send a PR just to fix this issue.

Comment (PipoCanaja) [reply tests/OSModulesTest.php]: Not 100% sure that the your PR code is run in this case, still unclear for me. But I removed the poller part in `tests/OSModulesTest.php` and we'll see how it behaves

File: tests/OSModulesTest.php [hunk 4]
```diff
@@ -98,9 +98,14 @@ public function testOS($os, $variant, $modules): void
         $this->requireSnmpsim();  // require snmpsim for tests
         // stub out Eventlog::log and Fping->ping, we don't need to store them for these tests
         $this->stubClasses();
+        // Order discovery modules
+        $modules = array_fill_keys(array_intersect(array_keys($this->discoveryModules), array_keys($modules)), true);
```
Comment (murrant) [inline tests/OSModulesTest.php:102]: Did you try without these? they should not be needed as the discovering and polling actually orders modules correctly 100% of the time now.

Comment (PipoCanaja) [reply tests/OSModulesTest.php:102]: Will do. 
And I'll open a dedicated PR if the QOS module orderBy is indeed fixing the error in [fee2cf1](https://github.com/librenms/librenms/pull/16856/commits/fee2cf1b7f7b42854332d5f63e12fa6d022b2446).

Comment (PipoCanaja) [reply tests/OSModulesTest.php:102]: QOS fix is good. PR on the way (and I remove it from here)

File: LibreNMS/Modules/Qos.php [hunk 5]
```diff
@@ -199,7 +199,7 @@ public function cleanup(Device $device): int
     public function dump(Device $device, string $type): ?array
     {
         return [
-            'qos' => $device->qos()->orderBy('title')
```
Comment (PipoCanaja) [inline LibreNMS/Modules/Qos.php:202]: will be reverted when https://github.com/librenms/librenms/pull/16938 is merged

**Comment by murrant** [comment]
I still don't understand how the discovery module order would be wrong.  Here is the code inside of [discover_device()](https://github.com/librenms/librenms/blob/master/includes/discovery/functions.inc.php#L126)

```php
$discovery_modules = ['core' => true] + Config::get('discovery_modules', []);
foreach ($discovery_modules as $module => $module_status) {
```

So it is exactly using the config order. (core first)

**Comment by PipoCanaja** [comment]
I am completely lost now ... I don't understand what's happening, and have no clue how to fix it. Will do the "echo and print" route to saturate my xterm of debug text :D unless anyone has a better idea

**Comment by laf** [comment]
Is this ready for review again now @PipoCanaja?

File: tests/OSModulesTest.php [hunk 6]
```diff
@@ -101,6 +101,7 @@ public function testOS($os, $variant, $modules): void
 
         try {
             Debug::set(false); // avoid all undefined index errors in the legacy code
+            $modules = array_fill_keys(array_intersect(array_keys($this->discoveryModules), array_keys($modules)), true);
```
Comment (PipoCanaja) [inline tests/OSModulesTest.php:104]: Well @laf, we still don't get why this exact line here is necessary.
But you can review the code (in Cisco.php and cisco-entity-sensor.inc.php), which are the useful parts of this PR :)

Comment (laf) [reply tests/OSModulesTest.php:104]: @PipoCanaja The code looks ok to me. Other than the test data I don't have access to any devices this impacts so I can't check any further.

I'd be happy to merge as is and thanks for all the effort you've put into it.

@librenms/core anyone else?

**Review by laf — APPROVED** [review]

File: tests/OSModulesTest.php (hunk 6 above)
Comment (PipoCanaja) [reply tests/OSModulesTest.php:104]: I'll try to do something about that next WE. When do you plan next release ? I would have liked to make it but it will be a little short I suppose.

Comment (laf) [reply tests/OSModulesTest.php:104]: What about just linking to this PR as a comment against that line in the code @PipoCanaja for future reference.

**Review by laf — APPROVED** [review]
LGTM. Great work @PipoCanaja

**Comment by PipoCanaja** [comment]
Thx for help guys, this order of processing drove me mad :)
