### PR TITLE
fix: meraki bad_uptime

### LINKED ISSUE #4691: Meraki AP always issues alerts for device rebooted
DO NOT DELETE THIS INFORMATION.

> Please read this information carefully.

- [X] Is your install up to date? [Updating your install](http://docs.librenms.org/General/Updating/)
      Please do not submit an issue if your install is not up to date within the last 24 hours or on a stable monthly release.
- [X] Please include all of the information between the `====================================` section of `./validate.php`.
- [ ] If you would like us to add a new device then please provide the information asked for [here](http://docs.librenms.org/Support/FAQ/#faq20)
- [X] Please provide as much detail as possible.

After fixing #4625, now these devices trow device rebooted alerts.
If you need any debugging outputs/logs, please let me know.

/Alex

### PR DESCRIPTION
**Pull request by crcro**
#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you signed the [Contributors agreement](http://docs.librenms.org/General/Contributing/)
- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

fixes: #4691

### CODE REVIEW

File: html/pages/front/default.php [hunk 1]
```diff
@@ -116,7 +116,7 @@ function generate_front_box($frontbox_class, $content)
 }
 
 // Device rebooted boxes
-if (filter_var($config['uptime_warning'], FILTER_VALIDATE_FLOAT) !== false && $config['uptime_warning'] > 0 && $config['os'][$os]['bad_uptime'] !== true) {
+if ((filter_var($config['uptime_warning'], FILTER_VALIDATE_FLOAT) !== false && $config['uptime_warning'] > 0) && $config['os'][$os]['bad_uptime'] !== true) {
```
Comment (laf) [inline html/pages/front/default.php]: How do these additional () make a difference here?

Comment (crcro) [inline html/pages/front/default.php]: my bad :) nothing at all  ...
push an updated code, i think that the issue is $config[''os"][$os]["bad_uptime"] is not available in that script so it will return always that bad_uptime !== true

**Comment by laf** [comment]
Why not just use `$config['os'][$os]['bad_uptime'] !== true` where `$device['os'] != "merakimr"` is? Seems to make more sense the way you'd started to do it.

**Comment by crcro** [comment]
because i've tried and that var is not available there, it is null/empty everytime

**Comment by laf** [comment]
In where, `includes/polling/core.inc.php` or `html/pages/front/default.php`?

**Comment by laf** [comment]
bump

**Comment by crcro** [comment]
i've tested the core.inc.php because in that file is the device status generated based on uptime

**Comment by laf** [comment]
That's because you're using `$config['os'][$os]['bad_uptime']` when it should be `$config['os'][$device['os']]['bad_uptime']`
