### PR TITLE
Fix: Add user level to getUser for LDAP authentication

### LINKED ISSUE #7893: LDAP (and AD?) auth getUser does not return level -> API fails
The newly added fake session for API authentication assumes that getUser will also return the user level. It does not for LDAP authentication, and probably neither for AD authentication. I don't know if the API fakes session should be changed (see https://community.librenms.org/t/new-api-restrictions-and-ldap-userlevel-issue/2772/2), or the user level should be added to all getUser functions.

API:
https://github.com/librenms/librenms/blob/9d66d7c8976adc175d1ac9a18537cab4a73cf4d6/html/includes/api_functions.inc.php#L25-L32

LDAP:
https://github.com/librenms/librenms/blob/6b5dccc169d529204066b5174392c8b74bd23bc0/LibreNMS/Authentication/LdapAuthorizer.php#L159-L164

AD:
https://github.com/librenms/librenms/blob/6b5dccc169d529204066b5174392c8b74bd23bc0/LibreNMS/Authentication/ActiveDirectoryAuthorizer.php#L219

### PR DESCRIPTION
**Pull request by Ultra2D**
DO NOT DELETE THIS TEXT

#### Please note

> Please read this information carefully. You can run `./scripts/pre-commit.php` to check your code before submitting.

- [x] Have you followed our [code guidelines?](http://docs.librenms.org/Developing/Code-Guidelines/)

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`

Fixes #7893.

### CODE REVIEW

File: LibreNMS/Authentication/LdapAuthorizer.php [hunk 1]
```diff
@@ -161,6 +161,7 @@ public function getUserlist()
                                 'realname' => $realname,
                                 'user_id' => $user_id,
                                 'email' => $email,
+                                'level' => $this->getUserlevel($username),
```
Comment (murrant) [inline LibreNMS/Authentication/LdapAuthorizer.php]: This is going to make getUserlist() even slower. Can you please add it on the getUser() function and make mark a TODO here.

Comment (Ultra2D) [reply LibreNMS/Authentication/LdapAuthorizer.php]: I am not sure why a TODO should be added to getUserlist (and what to write as a description of the TODO).

Maybe this fix should be added to #7718?

**Comment by laf** [comment]
@Ultra2D You will need to sign the CLA before we can merge this. Should just be a case of clicking the link in the comment from the bot above.
