### PR TITLE
fix: device edit legacy urls

### LINKED ISSUE #19102: Setting pages stop working due to URL error
### The problem

I've tested this on 2 installs and it seems to be the same. 
When opening the settings of a device page the url is:
https://noc.xxxx.com/device/188/edit

However when clicking around the url changes to:
https://noc.xxxx.com/device/device=188/tab=edit/section=apps

This causes the page not to load correctly

### Output of ./validate.php

```txt
na - tested on 2 installs.
```

### What was the last working version of LibreNMS?

26.3.0-dev.26

### Anything in the logs that might be useful for us?

```txt

```

### PR DESCRIPTION
**Pull request by chris9951**
When navigating to device edit sub-sections (e.g. /device/device=188/tab=edit/section=apps), the section parameter was not being parsed from the URL path, causing edit.inc.php to default to the 'device' section and fail to render content (device.inc.php does not exist).

Fix by parsing the full legacy URL path with Url::parseLegacyPath() before setting device and tab, consistent with how port tab vars are already handled in DeviceController::index().

Please give a short description what your pull request is for

DO NOT DELETE THE UNDERLYING TEXT

fixes #19102

#### Please note

> Please read this information carefully. You can run `./lnms dev:check` to check your code before submitting.

- [ ] Have you followed our [code guidelines?](https://docs.librenms.org/Developing/Code-Guidelines/)
- [ ] If my Pull Request does some changes/fixes/enhancements in the WebUI, I have inserted a screenshot of it.
- [ ] If my Pull Request makes discovery/polling/yaml changes, I have added/updated [test data](https://docs.librenms.org/Developing/os/Test-Units/).

#### Testers

If you would like to test this pull request then please run: `./scripts/github-apply <pr_id>`, i.e `./scripts/github-apply 5926`
After you are done testing, you can remove the changes with `./scripts/github-remove`.  If there are schema changes, you can ask on discord how to revert.

### CODE REVIEW

File: app/Http/Controllers/DeviceController.php [hunk 1]
```diff
@@ -69,6 +69,7 @@ private function renderLegacyTab($tab, Device $device, $data)
         $init_modules = ['web', 'auth'];
         require base_path('/includes/init.php');
 
+        $vars = Url::parseLegacyPath(request()->path())->all();
```
Comment (murrant) [inline app/Http/Controllers/DeviceController.php]: so you are overwriting $vars parsed by init.php?

**Review by murrant — APPROVED** [review]

**Comment by murrant** [comment]
There are actually two edit pages. you edited both, when only the links in the legacy pages were broken. :)
